## 数据源配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shangshare?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver


## Mybatis 配置
mybatis:
  typeAliasesPackage: com.springboot.domain
  mapperLocations: classpath:mapper/*.xml